<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <ApplicationIcon>res\icon.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="res\icon.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Lidgren.Network" Version="1.0.2" />
    <PackageReference Include="Raylib-cs" Version="6.0.0" />
  </ItemGroup>

  <ItemGroup>
    <None Update="res\icon.ico">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="res\icon.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="res\paddle.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="res\paddle_hit.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="res\score.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="res\wall_hit.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
